//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortezazadehDCM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EME : DbContext
    {
        public EME()
            : base("name=EME")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EsiBigData> EsiBigDatas { get; set; }
        public virtual DbSet<EsiCategory> EsiCategories { get; set; }
        public virtual DbSet<EsiField> EsiFields { get; set; }
        public virtual DbSet<EsiItem> EsiItems { get; set; }
        public virtual DbSet<EsiMetaType> EsiMetaTypes { get; set; }
        public virtual DbSet<EsiProduct> EsiProducts { get; set; }
        public virtual DbSet<EsiSynon> EsiSynons { get; set; }
    }
}
