//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortezazadehDCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsiCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EsiCategory()
        {
            this.EsiFields = new HashSet<EsiField>();
            this.EsiProducts = new HashSet<EsiProduct>();
            this.EsiSynons = new HashSet<EsiSynon>();
        }
    
        public decimal CateID { get; set; }
        public string CateName { get; set; }
        public string CateLabel { get; set; }
        public int CateState { get; set; }
        public int CateOrder { get; set; }
        public Nullable<decimal> CateParent { get; set; }
        public string CateDesc { get; set; }
        public string CateTname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EsiField> EsiFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EsiProduct> EsiProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EsiSynon> EsiSynons { get; set; }
    }
}
