//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortezazadehDCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsiItem
    {
        public decimal EsiObjId { get; set; }
        public decimal EsiFieldId { get; set; }
        public string EsiStrVal { get; set; }
    
        public virtual EsiField EsiField { get; set; }
        public virtual EsiProduct EsiProduct { get; set; }
    }
}
