//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortezazadehDCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsiMetaType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EsiMetaType()
        {
            this.EsiFields = new HashSet<EsiField>();
        }
    
        public int EsiMetaTypeId { get; set; }
        public string EsiMetaTypeName { get; set; }
        public int EsiMetaTypeState { get; set; }
        public string EsiMetaTypeDesc { get; set; }
        public int EsiMetaTypeOrder { get; set; }
        public string EsiMetaTypelabel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EsiField> EsiFields { get; set; }
    }
}
