//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortezazadehDCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsiProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EsiProduct()
        {
            this.EsiItems = new HashSet<EsiItem>();
        }
    
        public decimal EsiProductId { get; set; }
        public decimal EsiProductCateId { get; set; }
    
        public virtual EsiCategory EsiCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EsiItem> EsiItems { get; set; }
    }
}
