//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortezazadehDCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsiSynon
    {
        public decimal EsiSynonId { get; set; }
        public string EsiSynonName { get; set; }
        public decimal EsiSynonCateId { get; set; }
    
        public virtual EsiCategory EsiCategory { get; set; }
    }
}
